# Task 1

In [1]:
import numpy as np
X = np.array([
    [2.1598,2.1598,2.1701,2.1788],
    [2.1598,2.1701,2.1788,2.1727],
    [2.1701,2.1788,2.1727,2.1727],
    [2.1727,2.1727,2.1727,2.1727],
    [2.1727,2.1727,2.1727,2.1590],
    [2.1727,2.1727,2.1590,2.1569],
    [2.1727,2.1590,2.1569,2.1532],
    [2.1590,2.1569,2.1532,2.1503],
    [2.1569,2.1532,2.1503,2.1503]
])
y = np.array([
    [2.1727],
    [2.1727],
    [2.1727],
    [2.1727],
    [2.1590],
    [2.1532],
    [2.1503],
    [2.1503],
    [2.1503]
])


In [2]:
import numpy as np


def sigmoid(x, deriv=False):
    if deriv:
        return x * (1-x)
    return 1 / (1 + np.exp(-x))


class OneLayerNN:
    def __init__(self, x_len, y_len, n_neurons):
        self.layer1 = np.random.uniform(-1.0, 1.0, size=(x_len, n_neurons))
        self.layer2 = np.random.uniform(-1.0, 1.0, size=(n_neurons, y_len))
        
    
    def forward(self, X):
        l1 = sigmoid(np.dot(X, self.layer1))
        l2 = sigmoid(np.dot(l1, self.layer2))
        return l1, l2
    
    
    def backward(self, X, y, l1, l2):
        error = y - l2
        l2_delta = error * sigmoid(l2, True)
        l1_error = np.dot(l2_delta, self.layer2.T)
        l1_delta = l1_error * sigmoid(l1, True)
        self.layer2 += l1.T.dot(l2_delta)
        self.layer1 += X.T.dot(l1_delta)
        return error
    
    
    def train_iteration(self, X, y):
        l1, l2 = self.forward(X)
        return self.backward(X, y, l1, l2)

In [3]:
currency_nn = OneLayerNN(4, 1, 10)

X_norm = X / 3
y_norm = y / 3

for i in range(100000):
    error = currency_nn.train_iteration(X_norm, y_norm)
    if i % 10000 == 0:
        print(f'Error: {np.mean(np.abs(error))}')    

Error: 0.12322000008515793
Error: 0.0033798693892863607
Error: 0.0033273263194750274
Error: 0.0032764438025487553
Error: 0.0032268710361790737
Error: 0.003178257417619987
Error: 0.0031302613814269994
Error: 0.0030825596498163708
Error: 0.0030348559859367055
Error: 0.002986888790658362


In [4]:
X_test = np.array([[2.1532,2.1503,2.1503,2.1503],
              [2.1503,2.1503,2.1503,2.1503]]) / 3
y_test = np.array([[2.1503],
              [2.1503]])

_, y_pred = currency_nn.forward(X_test)
print(f'Real: {y_test}')
print(f'Prediction: {y_pred * 3}')

Real: [[2.1503]
 [2.1503]]
Prediction: [[2.16004594]
 [2.16035281]]


# Task 2

In [5]:
def normalize_weight(w):
    if w <= 0.5:
        return 0
    elif w > 0.5 and w <= 1:
        return 0.25
    elif w > 1 and w <= 2:
        return 0.5
    elif w > 2 and w <= 5:
        return 0.75
    else:
        return 1
    
def normalize_power(p):
    if p <= 20:
        return 0
    elif p > 20 and p <= 50:
        return 0.25
    elif p > 50 and p <= 100:
        return 0.5
    elif p > 100 and p <= 200:
        return 0.75
    else:
        return 1
    
def normalize_passengers(p):
    if p <= 2:
        return 0
    elif p > 2 and p <= 5:
        return 0.25
    elif p > 5 and p <= 10:
        return 0.5
    elif p > 10 and p <= 20:
        return 0.75
    else:
        return 1
    
def normalize_carrying(c):
    if c <= 1:
        return 0
    elif c > 1 and c <= 2:
        return 0.25
    elif c > 2 and c <= 3:
        return 0.5
    elif c > 3 and c <= 4:
        return 0.75
    else:
        return 1
    
def normalize(X):
    return np.hstack((np.array(list(map(normalize_weight, X[:, 0]))).reshape((X.shape[0], 1)), 
                      np.array(list(map(normalize_power, X[:, 1]))).reshape((X.shape[0], 1)), 
                      np.array(list(map(normalize_passengers, X[:, 2]))).reshape((X.shape[0], 1)), 
                      np.array(list(map(normalize_carrying, X[:, 3]))).reshape((X.shape[0], 1))))

In [6]:
X = np.array([
    [0.645,33,4,0.34],
    [2.880,152,14,1.5],
    [1.110,88,5,0.475],
    [10.400,260,3,6],
    [2.880,152,3,1.5],
    [9.895,122,30,6.2],
    [3.695,136,3,3],
    [2.170,116,5,0.6],
    [27.895,278,150,11]
])

y_norm = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])
X_norm = normalize(X)

In [8]:
truck_nn = OneLayerNN(4, 3, 10)
for i in range(100000):
    error = truck_nn.train_iteration(X_norm, y_norm)
    if i % 10000 == 0:
        print(f'Error: {np.mean(np.abs(error))}')

Error: 0.5356665504196761
Error: 0.003948686818300026
Error: 0.0026616590351242132
Error: 0.002119760020462624
Error: 0.0018055892574008444
Error: 0.0015952147008604363
Error: 0.00144212152341887
Error: 0.001324482356889778
Error: 0.0012305444526790556
Error: 0.0011533548762084637


In [12]:
X_test = np.array([[74,1050,1,90],
              [13.6,260,10,3],
              [0.3,40,3,0.25],
              [0.2,1,4,0.2],
              [0.02,0.3,1,0.1],
              [18.4,245,168,12]])

X_test_norm = normalize(X_test)
_, y_pred = truck_nn.forward(X_test_norm)
for i in range(y_pred.shape[0]):
    print(np.round(y_pred[i, :], 2))

[0. 0. 1.]
[0.   0.05 0.99]
[1.   0.01 0.  ]
[0.99 0.1  0.  ]
[0.99 0.   0.  ]
[0. 1. 0.]


# Task 3

In [13]:
X = np.array([
    [11000,11000,100100,1000010,1111110,1000010,1000010,1000010],
    [1111100,1000000,1000000,1111100,1000010,1000010,1000010,1111100],
    [1111100,1000010,1000010,1111100,1000010,1000010,1000010,1111100],
    [1111100,1000010,1000000,1000000,1000000,1000000,1000000,1000000],
    [11000,100100,100100,100100,100100,100100,1111110,1000010],
    [1111110,1000000,1000000,1111100,1000000,1000000,1000000,1111110],
    [1101011,101010,101010,11100,11100,101010,101010,1101011],
    [111100,1000010,10,11100,10,10,1000010,111100],
    [1000010,1000010,1000110,1001010,1010010,1100010,1000010,1000010],     
    [1000010,1000100,1001000,1010000,1110000,1001000,1000100,1000010],
    [110,1010,10010,10010,10010,10010,100010,1000010],
    [1000001,1100011,1010101,1001001,1000001,1000001,1000001,1000001],
    [1000010,1000010,1000010,1111110,1000010,1000010,1000010,1000010],
    [111100,1000010,1000010,1000010,1000010,1000010,1000010,111100],
    [1111110,1000010,1000010,1000010,1000010,1000010,1000010,1000010],
    [1111100,1000010,1000010,1111100,1000000,1000000,1000000,1000000],
    [111100,1000010,1000000,1000000,1000000,1000000,1000010,111100],
    [1111100,10000,10000,10000,10000,10000,10000,10000],
    [1000010,1000010,1000010,111110,10,10,1000010,111100],
    [1000,111110,1001001,1001001,111110,1000,1000,1000],
    [1000001,100010,10100,1000,1000,10100,100010,1000001],        
    [1000010,1000010,1000010,111110,10,10,10,10],
    [1001001,1001001,1001001,1001001,1001001,1001001,1001001,1111111],
    [1100000,100000,100000,111100,100001,100001,100001,111110],
    [1000001,1000001,1000001,1111001,1000101,1000101,1000101,1111001],
    [100000,100000,100000,111100,100001,100001,100001,111110],
    [111100,1000010,10,11110,10,10,1000010,111100],
    [1001110,1010001,1010001,1110001,1010001,1010001,1010001,1001110],
    [111110,1000010,1000010,111110,1010,10010,100010,1000010],
    [11000,10000,100100,1000010,1111110,1000010,1000010,1000001],
    [1111110,1000000,1000000,1111100,1000010,1000010,1000010,1111100],
    [1111100,1000010,1000010,1111100,1000010,1000010,1000010,111100],
    [1111100,1000010,1000000,1000000,0,1000000,1000000,1000000],
    [11000,100100,100100,100100,100100,100100,1110110,1000010],
    [1111110,1000000,1000000,1101100,1000000,1000000,1000000,1111110],
    [1101011,101010,101010,11100,10100,101010,101010,100011],
    [111100,1000010,10,11100,10,10,1000010,110100],
    [1000010,1000010,1000110,1000010,1010010,1100010,1000010,1000010],
    [1000001,1000100,1001000,1010000,1110000,1001000,1000100,1000010],
    [110,1010,10010,10010,10010,10010,100010,1000000],
    [1000001,1100011,1010101,1001001,1000001,1000001,1000001,1000000],
    [1000010,1000010,1000010,1101110,1000010,1000010,1000010,1000010],
    [110100,1000010,1000010,1000010,1000010,1000010,1000010,111100],
    [1111110,1000010,1000010,1000010,1000010,1000010,1000010,1000000],
    [1101100,1000010,1000010,1111100,1000000,1000000,1000000,1000000],
    [110100,1000010,1000000,1000000,1000000,1000000,1000010,111100],
    [1111111,10000,10000,10000,10000,10000,10000,10000],
    [1000010,1000010,1000010,111010,10,10,1000010,111100],
    [1000,111110,1001001,1001001,110110,1000,1000,1000],
    [1000001,100010,10100,1000,1000,10100,100010,1001001],
    [1000010,1000010,1000010,111110,10,10,10,0],
    [1001001,1001001,1001001,1001001,1001001,1001001,1001001,1110111],
    [1100000,0,100000,111100,100001,100001,100001,111110],
    [1000001,1000001,1000001,1111001,1000101,1000101,1000100,1111001],
    [100000,100000,100000,111100,100001,100001,100001,110110],
    [111110,1000010,10,11110,10,10,1000010,111100],
    [1001110,1010001,1010001,1110001,1010001,1010001,1010001,1001011],
    [111110,1000010,1000010,111110,1010,10010,100010,1000000]
])

y = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
              [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [15]:
X.shape

(58, 8)

In [18]:
y.shape

(58, 29)

In [22]:
letter_nn = OneLayerNN(8, 29, 5)
for i in range(10000):
    error = letter_nn.train_iteration(X, y)
    if i % 1000 == 0:
        print(f'Error: {np.mean(np.abs(error))}')

/Users/andreiklitsunou/.pyenv/versions/3.6.6/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in exp
  import sys


Error: 0.5638481506436351
Error: 0.03947537674634518
Error: 0.04106389943652926
Error: 0.04125890321224184
Error: 0.04111839841699044
Error: 0.041055539775316334
Error: 0.04117940397236246
Error: 0.041856677148833815
Error: 0.040790998020870425
Error: 0.04064973600345177


In [23]:
X_test = [
    [1000010,1000100,1001000,1010000,1110000,1001000,1000100,1000010],
    [11000,11000,100100,1000010,1111110,1000010,1000010,1000010],
    [1111100,1000010,1000010,1111100,1000010,1000010,1000010,1111100],
]

_, y_pred = letter_nn.forward(X_test)

/Users/andreiklitsunou/.pyenv/versions/3.6.6/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in exp
  import sys


In [25]:
y_pred.round(1)

array([[0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ]])